#!/usr/bin/env bash

REGRESSION_SUBSCRIPTION_STATE_SUITE_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
PADM_REGRESSION_SOURCE_ONLY=1 source "${REGRESSION_SUBSCRIPTION_STATE_SUITE_DIR}/../subscription_groups_subscription_state_full.sh"

while read -r selector runner; do
    registerRegressionFunctionLeaf "${selector}" "${runner}"
done <<'EOF'
subscription-state-serial runRegressionSubscriptionStateSerial
subscription-state-structure runRegressionSubscriptionStateStructure
subscription-state-structure-foundation runRegressionSubscriptionStateStructureFoundation
subscription-state-structure-foundation-add-remove runRegressionSubscriptionStateStructureFoundationAddRemove
subscription-state-structure-foundation-credential runRegressionSubscriptionStateStructureFoundationCredential
subscription-state-structure-foundation-normalize runRegressionSubscriptionStateStructureFoundationNormalize
subscription-state-structure-foundation-init-transaction runRegressionSubscriptionStateStructureFoundationInitTransaction
subscription-state-structure-foundation-serial runRegressionSubscriptionStateStructureFoundationSerial
subscription-state-structure-migration runRegressionSubscriptionStateStructureMigration
subscription-state-structure-source runRegressionSubscriptionStateStructureSource
subscription-state-structure-source-credential runRegressionSubscriptionStateStructureSourceCredential
subscription-state-structure-source-status runRegressionSubscriptionStateStructureSourceStatus
subscription-state-structure-source-remove runRegressionSubscriptionStateStructureSourceRemove
subscription-state-structure-source-serial runRegressionSubscriptionStateStructureSourceSerial
subscription-state-structure-serial runRegressionSubscriptionStateStructureSerial
subscription-state-quota runRegressionSubscriptionStateQuota
subscription-state-quota-traffic runRegressionSubscriptionStateQuotaTraffic
subscription-state-quota-traffic-summary runRegressionSubscriptionStateQuotaTrafficSummary
subscription-state-quota-traffic-invalid-input runRegressionSubscriptionStateQuotaTrafficInvalidInput
subscription-state-quota-traffic-apply runRegressionSubscriptionStateQuotaTrafficApply
subscription-state-quota-traffic-serial runRegressionSubscriptionStateQuotaTrafficSerial
subscription-state-quota-menu-preview-fail runRegressionSubscriptionStateQuotaMenuPreviewFailure
subscription-state-quota-menu-tx runRegressionSubscriptionStateQuotaMenuTransaction
subscription-state-quota-menu-tx-rollback runRegressionSubscriptionStateQuotaTransactionRollback
subscription-state-quota-menu-tx-serial runRegressionSubscriptionStateQuotaMenuTransactionSerial
subscription-state-quota-partial-sync runRegressionSubscriptionStateQuotaPartialSync
subscription-state-quota-partial-sync-apply-failure runRegressionSubscriptionStateQuotaPartialSyncApplyFailure
subscription-state-quota-partial-sync-plan runRegressionSubscriptionStateQuotaPartialSyncPlan
subscription-state-quota-partial-sync-config runRegressionSubscriptionStateQuotaPartialSyncConfig
subscription-state-quota-partial-sync-serial runRegressionSubscriptionStateQuotaPartialSyncSerial
subscription-state-quota-serial runRegressionSubscriptionStateQuotaSerial
subscription-state-remote-restore runRegressionSubscriptionStateRemoteRestore
subscription-state-remote-restore-self-reference runRegressionSubscriptionStateRemoteRestoreSelfReference
subscription-state-remote-restore-self-reference-plan runRegressionSubscriptionStateRemoteRestoreSelfReferencePlan
subscription-state-remote-restore-self-reference-sync runRegressionSubscriptionStateRemoteRestoreSelfReferenceSync
subscription-state-remote-restore-self-reference-serial runRegressionSubscriptionStateRemoteRestoreSelfReferenceSerial
subscription-state-remote-restore-state-write runRegressionSubscriptionStateRemoteRestoreStateWrite
subscription-state-remote-restore-legacy-menu runRegressionSubscriptionStateRemoteRestoreLegacyMenu
subscription-state-remote-restore-serial runRegressionSubscriptionStateRemoteRestoreSerial
subscription-state-support runRegressionSubscriptionStateSupport
subscription-state-sync-rollback runRegressionSubscriptionStateSyncRollback
subscription-state-sync-rollback-serial runRegressionSubscriptionStateSyncRollbackSerial
subscription-sync-tempdir runRegressionSubscriptionSyncTempDir
subscription-sync-rollback-failure runRegressionSubscriptionStateSyncRollback
subscription-sync-rollback-failure-serial runRegressionSubscriptionStateSyncRollbackSerial
subscription-sync-rollback-config-restore-failure runRegressionSubscriptionSyncRollbackConfigRestoreFailure
subscription-sync-restore-dir-failure runRegressionSubscriptionSyncRollbackRestoreDirFailure
subscription-sync-reload-rollback runRegressionSubscriptionSyncRollbackReloadRollback
subscription-group-sync-rollback runRegressionSubscriptionGroupSyncRollback
subscription-group-sync-rollback-serial runRegressionSubscriptionGroupSyncRollbackSerial
subscription-group-sync-apply-failure runRegressionSubscriptionGroupSyncApplyFailure
subscription-group-sync-reconcile-rollback runRegressionSubscriptionGroupSyncReconcileRollback
subscription-group-sync-remote-failure runRegressionSubscriptionGroupSyncRemoteFailure
subscription-sync-reconcile-early-exit runRegressionSubscriptionSyncReconcileEarlyExit
subscription-groups-restore-failure runRegressionSubscriptionGroupsRestoreFailure
EOF

listRegressionSubscriptionStateCoreChildSelectors() {
    printf '%s\n' \
        subscription-state-structure \
        subscription-state-quota \
        subscription-state-remote-restore
}

listRegressionSubscriptionStateChildSelectors() {
    printf '%s\n' \
        subscription-state-core \
        subscription-state-support \
        subscription-state-sync-rollback
}

registerRegressionAggregateRunnerParallel subscription-state-core runRegressionSubscriptionStateCore \
    $(listRegressionSubscriptionStateCoreChildSelectors)
registerRegressionAggregateRunnerParallel subscription-state runRegressionSubscriptionState \
    $(listRegressionSubscriptionStateChildSelectors)
